### ISSUE TITLE
getting IndexOutOfBoundsException during compression

### ISSUE THREAD

**Issue by pilaszyistvan** [lemire/JavaFastPFOR#36]
I have the following code:
```
import java.nio.file.*;
import java.util.stream.Stream;
import me.lemire.integercompression.differential.IntegratedIntCompressor;
public class Proba {
        public static void main(String[] args) throws Exception {
                int[] data = Files.lines(Paths.get("integers.txt")).mapToInt(Integer::parseInt).toArray();
                System.out.println("Read " + data.length + " integers");
                IntegratedIntCompressor iic = new IntegratedIntCompressor();
                int[] compressed = iic.compress(data);
        }
}
```
I run the following command:
java -cp .:JavaFastPFOR-0.1.9.jar Proba

And I get the following output:
```
Read 130657 integers
Exception in thread "main" java.lang.IndexOutOfBoundsException
        at java.nio.Buffer.checkBounds(Buffer.java:567)
        at java.nio.DirectIntBufferU.get(DirectIntBufferU.java:265)
        at me.lemire.integercompression.differential.IntegratedVariableByte.headlessCompress(IntegratedVariableByte.java:222)
        at me.lemire.integercompression.differential.SkippableIntegratedComposition.headlessCompress(SkippableIntegratedComposition.java:58)
        at me.lemire.integercompression.differential.IntegratedIntCompressor.compress(IntegratedIntCompressor.java:42)
        at Proba.main(Proba.java:9)
```

Output of 'java -version':
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Please find attached the 'integers.txt' containing the integer numbers. I tried to make it smaller, the original array contained 1 million elements, now it contains "only" 130657 integers, but I cannot reduce its size further.

[integers.txt](https://github.com/lemire/JavaFastPFOR/files/515521/integers.txt)

**Comment by lemire** [comment]
Fixed in 0.1.10. 

Note that your test data is not sorted so you will not get practical results with IntegratedIntCompressor. You'll probably have better luck with IntCompressor.
